#!/bin/bash

#YO api token for authentication
YO_TOKEN=b361d985-ed35-4ae1-81b0-d570e8819c20
#Yo username to send to
YO_USERNAME=MALOMARO


output=$("${@:1}")

#echo $output

output=$(echo "key=public&paste=$("${@:1}")" | curl -d @- http://paste.ee/api)


string=$( echo $output | cut -c12-18 )
if [ $string = "success" ]; then
    paste_url=$( echo $output | cut -c36-40 )
    echo $paste_url
    ./yo $YO_TOKEN -t $YO_USERNAME -u "http://paste.ee/p/$paste_url"
fi


echo "Done"
